# Generated by Django 5.1.3 on 2024-11-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('intra', 'Intra')], default='email', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.ManyToManyField(related_name='users', to='auth_users.authprovider'),
        ),
    ]
