# Generated by Django 5.1.3 on 2025-03-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_alter_friends_block_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='block_action',
        ),
    ]
