# Generated by Django 5.1.3 on 2025-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_alter_authprovider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authprovider',
            name='name',
            field=models.CharField(choices=[('Email', 'email'), ('Google', 'google'), ('Intra', 'intra')], default='Email', max_length=50, unique=True),
        ),
    ]
