# Generated by Django 5.1.3 on 2025-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0005_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.ManyToManyField(related_name='auth_provider', to='auth_users.authprovider'),
        ),
    ]
