
networks:
  TransNetwork:
    name: "TransNetwork"

volumes:
  users-data:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "/tmp/users_data"
  auth_redis_data:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "/tmp/auth_redis_data"
  api_redis_data:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "/tmp/api_redis_data"
  redisinsight_data:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "/tmp/redisinsight"
  frontend-volume:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "./frontend/public"
  auth-service-code:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "./auth_build/auth_service"
  api-service-code:
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: "./api_build/api_service"

services:
  users-db:
    image: postgres
    container_name: users_db
    networks:
      - TransNetwork
    volumes:
      - users-data:/var/lib/postgresql/data
    env_file:
      - "auth_build/build/conf/.env"
  
  auth-service:
    build: "auth_build/."
    pull_policy: build
    image: auth_service:latest
    container_name: auth_service
    networks:
      - TransNetwork
    depends_on:
      - users-db
      - auth-redis
      - api-service
    env_file:
      - "auth_build/build/conf/.env"
    volumes:
      - "auth-service-code:/var/app"

  api-service:
    build: "api_build/."
    pull_policy: build
    image: api_service:latest
    container_name: api_service
    networks:
      - TransNetwork
    depends_on:
      - rabbitmq
      - api-redis
    volumes:
      - "api-service-code:/var/app/"

  api-redis:
    build: "api_redis"
    pull_policy: build
    image: api_redis
    container_name: api_redis
    networks:
      - TransNetwork
    volumes:
      - "api_redis_data:/data"

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - TransNetwork

  nginx:
    image: nginx:latest
    pull_policy: build
    build: "nginx/."
    container_name: nginx_reverse
    ports:
      - 8000:80
    depends_on:
      - auth-service
      - adminer
      - api-service
    networks:
      - TransNetwork

  adminer:
    image: adminer
    container_name: adminer_inspect
    networks:
      - TransNetwork
    depends_on:
      - users-db
    env_file:
     - adminer/.env
  
  auth-redis:
    build: "auth_redis"
    pull_policy: build
    image: auth_redis_image
    container_name: auth_redis
    networks:
      - TransNetwork
    volumes:
      - "auth_redis_data:/data"

  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    networks:
      - TransNetwork
    ports:
      - 5540:5540
    depends_on:
      - auth-redis
    volumes:
      - "redisinsight_data:/data"

  frontend:
    container_name: frontend
    build : "frontend/."
    image: frontend:latest
    pull_policy: build
    networks:
      - TransNetwork
    init : true # handle correctly signals for node js container
    depends_on:
      - auth-service
    volumes:
      - "frontend-volume:/app/src"
