# Generated by Django 5.1.4 on 2025-02-26 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField()),
                ('status', models.CharField(choices=[('read', 'Read'), ('delivered', 'Delivered')], default='delivered', max_length=10)),
                ('user', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
