# Generated by Django 5.1.4 on 2025-03-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
