# Generated by Django 5.1.4 on 2025-03-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0002_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=400),
        ),
    ]
