# Generated by Django 5.1.4 on 2025-03-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0003_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
    ]
