# Generated by Django 5.1.4 on 2025-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0004_remove_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=400),
        ),
    ]
