# Generated by Django 5.1.2 on 2025-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
