# Generated by Django 5.1.2 on 2025-02-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
