# Generated by Django 5.1.2 on 2025-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_recipient_alter_message_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
